name: Code Check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: ?? Клонируем код
        uses: actions/checkout@v4

      - name: ?? Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ?? Устанавливаем зависимости
        run: |
          pip install flake8

      - name: ?? Проверка кода (flake8)
        run: |
          flake8 .